version: '2'

services:
    http-tunnel:
        build: 
            context: .
        environment:
            - SSH_HOSTUSER=tart
            - SSH_HOSTNAME=tart.elec.ac.nz
            - SSH_TUNNEL_REMOTE=8002
            - SSH_TUNNEL_LOCAL=80
        restart: always
        volumes:
            - ~/.ssh/id_rsa:/id_rsa
