# Run this with
#    docker-compose exec casa /bin/bash
# and you will find the measurement set in the /remote directory
version: '3.5'

services:

  casa:
    container_name: casa
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/remote'
      - ${XAUTHORITY}:/tmp/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.Xauthority
      - QT_X11_NO_MITSHM=1
      - LIBOVERLAY_SCROLLBAR=0
